export interface LocationOption {
  id: string;
  name: string;
}

export const LOCATIONS_LIST: LocationOption[] = [
  // States & Union Territories
  { id: 'andhra-pradesh', name: 'Andhra Pradesh' },
  { id: 'arunachal-pradesh', name: 'Arunachal Pradesh' },
  { id: 'assam', name: 'Assam' },
  { id: 'bihar', name: 'Bihar' },
  { id: 'chhattisgarh', name: 'Chhattisgarh' },
  { id: 'goa', name: 'Goa' },
  { id: 'gujarat', name: 'Gujarat' },
  { id: 'haryana', name: 'Haryana' },
  { id: 'himachal-pradesh', name: 'Himachal Pradesh' },
  { id: 'jharkhand', name: 'Jharkhand' },
  { id: 'karnataka', name: 'Karnataka' },
  { id: 'kerala', name: 'Kerala' },
  { id: 'madhya-pradesh', name: 'Madhya Pradesh' },
  { id: 'maharashtra', name: 'Maharashtra' },
  { id: 'manipur', name: 'Manipur' },
  { id: 'meghalaya', name: 'Meghalaya' },
  { id: 'mizoram', name: 'Mizoram' },
  { id: 'nagaland', name: 'Nagaland' },
  { id: 'odisha', name: 'Odisha' },
  { id: 'punjab', name: 'Punjab' },
  { id: 'rajasthan', name: 'Rajasthan' },
  { id: 'sikkim', name: 'Sikkim' },
  { id: 'tamil-nadu', name: 'Tamil Nadu' },
  { id: 'telangana', name: 'Telangana' },
  { id: 'tripura', name: 'Tripura' },
  { id: 'uttar-pradesh', name: 'Uttar Pradesh' },
  { id: 'uttarakhand', name: 'Uttarakhand' },
  { id: 'west-bengal', name: 'West Bengal' },
  { id: 'andaman-nicobar', name: 'Andaman and Nicobar Islands' },
  { id: 'chandigarh', name: 'Chandigarh' },
  { id: 'dadra-nagar-haveli', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { id: 'delhi', name: 'Delhi' },
  { id: 'jammu-kashmir', name: 'Jammu and Kashmir' },
  { id: 'ladakh', name: 'Ladakh' },
  { id: 'lakshadweep', name: 'Lakshadweep' },
  { id: 'puducherry', name: 'Puducherry' },

  // Major Cities
  { id: 'mumbai', name: 'Mumbai, Maharashtra' },
  { id: 'delhi-city', name: 'New Delhi, Delhi' },
  { id: 'bangalore', name: 'Bangalore, Karnataka' },
  { id: 'hyderabad', name: 'Hyderabad, Telangana' },
  { id: 'ahmedabad', name: 'Ahmedabad, Gujarat' },
  { id: 'chennai', name: 'Chennai, Tamil Nadu' },
  { id: 'kolkata', name: 'Kolkata, West Bengal' },
  { id: 'surat', name: 'Surat, Gujarat' },
  { id: 'pune', name: 'Pune, Maharashtra' },
  { id: 'jaipur', name: 'Jaipur, Rajasthan' },
  { id: 'lucknow', name: 'Lucknow, Uttar Pradesh' },
  { id: 'kanpur', name: 'Kanpur, Uttar Pradesh' },
  { id: 'nagpur', name: 'Nagpur, Maharashtra' },
  { id: 'indore', name: 'Indore, Madhya Pradesh' },
  { id: 'thane', name: 'Thane, Maharashtra' },
  { id: 'bhopal', name: 'Bhopal, Madhya Pradesh' },
  { id: 'visakhapatnam', name: 'Visakhapatnam, Andhra Pradesh' },
  { id: 'pimpri-chinchwad', name: 'Pimpri-Chinchwad, Maharashtra' },
  { id: 'patna', name: 'Patna, Bihar' },
  { id: 'vadodara', name: 'Vadodara, Gujarat' },
  { id: 'ghaziabad', name: 'Ghaziabad, Uttar Pradesh' },
  { id: 'ludhiana', name: 'Ludhiana, Punjab' },
  { id: 'agra', name: 'Agra, Uttar Pradesh' },
  { id: 'nashik', name: 'Nashik, Maharashtra' },
  { id: 'faridabad', name: 'Faridabad, Haryana' },
  { id: 'meerut', name: 'Meerut, Uttar Pradesh' },
  { id: 'rajkot', name: 'Rajkot, Gujarat' },
  { id: 'kalyan-dombivli', name: 'Kalyan-Dombivli, Maharashtra' },
  { id: 'vasai-virar', name: 'Vasai-Virar, Maharashtra' },
  { id: 'varanasi', name: 'Varanasi, Uttar Pradesh' },
  { id: 'srinagar', name: 'Srinagar, Jammu and Kashmir' },
  { id: 'aurangabad', name: 'Aurangabad, Maharashtra' },
  { id: 'dhanbad', name: 'Dhanbad, Jharkhand' },
  { id: 'amritsar', name: 'Amritsar, Punjab' },
  { id: 'navi-mumbai', name: 'Navi Mumbai, Maharashtra' },
  { id: 'allahabad', name: 'Allahabad, Uttar Pradesh' },
  { id: 'ranchi', name: 'Ranchi, Jharkhand' },
  { id: 'howrah', name: 'Howrah, West Bengal' },
  { id: 'coimbatore', name: 'Coimbatore, Tamil Nadu' },
  { id: 'jabalpur', name: 'Jabalpur, Madhya Pradesh' },
  { id: 'gwalior', name: 'Gwalior, Madhya Pradesh' },
  { id: 'vijayawada', name: 'Vijayawada, Andhra Pradesh' },
  { id: 'jodhpur', name: 'Jodhpur, Rajasthan' },
  { id: 'madurai', name: 'Madurai, Tamil Nadu' },
  { id: 'raipur', name: 'Raipur, Chhattisgarh' },
  { id: 'kota', name: 'Kota, Rajasthan' },
  { id: 'guwahati', name: 'Guwahati, Assam' },
  { id: 'chandigarh-city', name: 'Chandigarh, Chandigarh' },
  { id: 'solapur', name: 'Solapur, Maharashtra' },
  { id: 'hubli-dharwad', name: 'Hubli-Dharwad, Karnataka' },
  { id: 'bareilly', name: 'Bareilly, Uttar Pradesh' },
  { id: 'moradabad', name: 'Moradabad, Uttar Pradesh' },
  { id: 'mysore', name: 'Mysore, Karnataka' },
  { id: 'gurgaon', name: 'Gurgaon, Haryana' },
  { id: 'aligarh', name: 'Aligarh, Uttar Pradesh' },
  { id: 'jalandhar', name: 'Jalandhar, Punjab' },
  { id: 'tiruchirappalli', name: 'Tiruchirappalli, Tamil Nadu' },
  { id: 'bhubaneswar', name: 'Bhubaneswar, Odisha' },
  { id: 'salem', name: 'Salem, Tamil Nadu' },
  { id: 'mira-bhayandar', name: 'Mira-Bhayandar, Maharashtra' },
  { id: 'warangal', name: 'Warangal, Telangana' },
  { id: 'thiruvananthapuram', name: 'Thiruvananthapuram, Kerala' },
  { id: 'bhiwandi', name: 'Bhiwandi, Maharashtra' },
  { id: 'saharanpur', name: 'Saharanpur, Uttar Pradesh' },
  { id: 'guntur', name: 'Guntur, Andhra Pradesh' },
  { id: 'amravati', name: 'Amravati, Maharashtra' },
  { id: 'bikaner', name: 'Bikaner, Rajasthan' },
  { id: 'noida', name: 'Noida, Uttar Pradesh' },
  { id: 'jamshedpur', name: 'Jamshedpur, Jharkhand' },
  { id: 'bhilai', name: 'Bhilai, Chhattisgarh' },
  { id: 'cuttack', name: 'Cuttack, Odisha' },
  { id: 'firozabad', name: 'Firozabad, Uttar Pradesh' },
  { id: 'kochi', name: 'Kochi, Kerala' },
  { id: 'bhavnagar', name: 'Bhavnagar, Gujarat' },
  { id: 'dehradun', name: 'Dehradun, Uttarakhand' },
  { id: 'durgapur', name: 'Durgapur, West Bengal' },
  { id: 'asansol', name: 'Asansol, West Bengal' },
  { id: 'nanded', name: 'Nanded, Maharashtra' },
  { id: 'kolhapur', name: 'Kolhapur, Maharashtra' },
  { id: 'ajmer', name: 'Ajmer, Rajasthan' },
  { id: 'gulbarga', name: 'Gulbarga, Karnataka' },
  { id: 'jamnagar', name: 'Jamnagar, Gujarat' },
  { id: 'ujjain', name: 'Ujjain, Madhya Pradesh' },
  { id: 'loni', name: 'Loni, Uttar Pradesh' },
  { id: 'siliguri', name: 'Siliguri, West Bengal' },
  { id: 'jhansi', name: 'Jhansi, Uttar Pradesh' },
  { id: 'ulhasnagar', name: 'Ulhasnagar, Maharashtra' },
  { id: 'nellore', name: 'Nellore, Andhra Pradesh' },
  { id: 'jammu', name: 'Jammu, Jammu and Kashmir' },
  { id: 'sangli-miraj-kupwad', name: 'Sangli-Miraj & Kupwad, Maharashtra' },
  { id: 'belgaum', name: 'Belgaum, Karnataka' },
  { id: 'mangalore', name: 'Mangalore, Karnataka' },
  { id: 'ambattur', name: 'Ambattur, Tamil Nadu' },
  { id: 'tirunelveli', name: 'Tirunelveli, Tamil Nadu' },
  { id: 'malegaon', name: 'Malegaon, Maharashtra' },
  { id: 'gaya', name: 'Gaya, Bihar' },
  { id: 'jalgaon', name: 'Jalgaon, Maharashtra' },
  { id: 'udaipur', name: 'Udaipur, Rajasthan' },
  { id: 'maheshtala', name: 'Maheshtala, West Bengal' },
  { id: 'tirupur', name: 'Tirupur, Tamil Nadu' },
  { id: 'davanagere', name: 'Davanagere, Karnataka' },
  { id: 'kozhikode', name: 'Kozhikode, Kerala' },
  { id: 'akola', name: 'Akola, Maharashtra' },
  { id: 'kurnool', name: 'Kurnool, Andhra Pradesh' },
  { id: 'rajpur-sonarpur', name: 'Rajpur Sonarpur, West Bengal' },
  { id: 'bokaro', name: 'Bokaro, Jharkhand' },
  { id: 'south-dumdum', name: 'South Dumdum, West Bengal' },
  { id: 'bellary', name: 'Bellary, Karnataka' },
  { id: 'patiala', name: 'Patiala, Punjab' },
  { id: 'gopalpur', name: 'Gopalpur, West Bengal' },
  { id: 'agartala', name: 'Agartala, Tripura' },
  { id: 'bhagalpur', name: 'Bhagalpur, Bihar' },
  { id: 'muzaffarnagar', name: 'Muzaffarnagar, Uttar Pradesh' },
  { id: 'bhatpara', name: 'Bhatpara, West Bengal' },
  { id: 'panihati', name: 'Panihati, West Bengal' },
  { id: 'latur', name: 'Latur, Maharashtra' },
  { id: 'dhule', name: 'Dhule, Maharashtra' },
  { id: 'rohtak', name: 'Rohtak, Haryana' },
  { id: 'korba', name: 'Korba, Chhattisgarh' },
  { id: 'bhilwara', name: 'Bhilwara, Rajasthan' },
  { id: 'berhampur', name: 'Berhampur, Odisha' },
  { id: 'muzaffarpur', name: 'Muzaffarpur, Bihar' },
  { id: 'ahmednagar', name: 'Ahmednagar, Maharashtra' },
  { id: 'mathura', name: 'Mathura, Uttar Pradesh' },
  { id: 'kollam', name: 'Kollam, Kerala' },
  { id: 'avadi', name: 'Avadi, Tamil Nadu' },
  { id: 'kadapa', name: 'Kadapa, Andhra Pradesh' },
  { id: 'rajamahmundry', name: 'Rajamahmundry, Andhra Pradesh' },
  { id: 'bilaspur', name: 'Bilaspur, Chhattisgarh' },
  { id: 'shahjahanpur', name: 'Shahjahanpur, Uttar Pradesh' },
  { id: 'bijapur', name: 'Bijapur, Karnataka' },
  { id: 'rampur', name: 'Rampur, Uttar Pradesh' },
  { id: 'shivamogga', name: 'Shivamogga, Karnataka' },
  { id: 'chandrapur', name: 'Chandrapur, Maharashtra' },
  { id: 'junagadh', name: 'Junagadh, Gujarat' },
  { id: 'thrissur', name: 'Thrissur, Kerala' },
  { id: 'alwar', name: 'Alwar, Rajasthan' },
  { id: 'bardhaman', name: 'Bardhaman, West Bengal' },
  { id: 'kulti', name: 'Kulti, West Bengal' },
  { id: 'kakinada', name: 'Kakinada, Andhra Pradesh' },
  { id: 'nizamabad', name: 'Nizamabad, Telangana' },
  { id: 'parbhani', name: 'Parbhani, Maharashtra' },
  { id: 'tumkur', name: 'Tumkur, Karnataka' },
  { id: 'khammam', name: 'Khammam, Telangana' },
  { id: 'uzhavoor', name: 'Uzhavoor, Kerala' },
  { id: 'bihar-sharif', name: 'Bihar Sharif, Bihar' },
  { id: 'panipat', name: 'Panipat, Haryana' },
  { id: 'darbhanga', name: 'Darbhanga, Bihar' },
  { id: 'bally', name: 'Bally, West Bengal' },
  { id: 'aizawl', name: 'Aizawl, Mizoram' },
  { id: 'dewas', name: 'Dewas, Madhya Pradesh' },
  { id: 'ichalkaranji', name: 'Ichalkaranji, Maharashtra' },
  { id: 'karnal', name: 'Karnal, Haryana' },
  { id: 'bathinda', name: 'Bathinda, Punjab' },
  { id: 'jalna', name: 'Jalna, Maharashtra' },
  { id: 'eluru', name: 'Eluru, Andhra Pradesh' },
  { id: 'barasat', name: 'Barasat, West Bengal' },
  { id: 'kirari-suleman-nagar', name: 'Kirari Suleman Nagar, Delhi' },
  { id: 'purnia', name: 'Purnia, Bihar' },
  { id: 'satna', name: 'Satna, Madhya Pradesh' },
  { id: 'mau', name: 'Mau, Uttar Pradesh' },
  { id: 'sonipat', name: 'Sonipat, Haryana' },
  { id: 'farrukhabad', name: 'Farrukhabad, Uttar Pradesh' },
  { id: 'sagar', name: 'Sagar, Madhya Pradesh' },
  { id: 'rourkela', name: 'Rourkela, Odisha' },
  { id: 'durg', name: 'Durg, Chhattisgarh' },
  { id: 'imphal', name: 'Imphal, Manipur' },
  { id: 'ratlam', name: 'Ratlam, Madhya Pradesh' },
  { id: 'hapur', name: 'Hapur, Uttar Pradesh' },
  { id: 'anantapur', name: 'Anantapur, Andhra Pradesh' },
  { id: 'arrah', name: 'Arrah, Bihar' },
  { id: 'karimnagar', name: 'Karimnagar, Telangana' },
  { id: 'etawah', name: 'Etawah, Uttar Pradesh' },
  { id: 'ambernath', name: 'Ambernath, Maharashtra' },
  { id: 'north-dumdum', name: 'North Dumdum, West Bengal' },
  { id: 'bharatpur', name: 'Bharatpur, Rajasthan' },
  { id: 'begusarai', name: 'Begusarai, Bihar' },
  { id: 'new-delhi', name: 'New Delhi, Delhi' },
  { id: 'gandhidham', name: 'Gandhidham, Gujarat' },
  { id: 'baranagar', name: 'Baranagar, West Bengal' },
  { id: 'tiruvottiyur', name: 'Tiruvottiyur, Tamil Nadu' },
  { id: 'puducherry-city', name: 'Puducherry, Puducherry' },
  { id: 'sikar', name: 'Sikar, Rajasthan' },
  { id: 'thoothukudi', name: 'Thoothukudi, Tamil Nadu' },
  { id: 'rewa', name: 'Rewa, Madhya Pradesh' },
  { id: 'mirzapur', name: 'Mirzapur, Uttar Pradesh' },
  { id: 'raichur', name: 'Raichur, Karnataka' },
  { id: 'pali', name: 'Pali, Rajasthan' },
  { id: 'ramagundam', name: 'Ramagundam, Telangana' },
  { id: 'haridwar', name: 'Haridwar, Uttarakhand' },
  { id: 'vijayanagaram', name: 'Vijayanagaram, Andhra Pradesh' },
  { id: 'katihar', name: 'Katihar, Bihar' },
  { id: 'nagercoil', name: 'Nagercoil, Tamil Nadu' },
  { id: 'sri-ganganagar', name: 'Sri Ganganagar, Rajasthan' },
  { id: 'karawal-nagar', name: 'Karawal Nagar, Delhi' },
  { id: 'mango', name: 'Mango, Jharkhand' },
  { id: 'thanjavur', name: 'Thanjavur, Tamil Nadu' },
  { id: 'bulandshahr', name: 'Bulandshahr, Uttar Pradesh' },
  { id: 'uluberia', name: 'Uluberia, West Bengal' },
  { id: 'murwara', name: 'Murwara, Madhya Pradesh' },
  { id: 'sambhal', name: 'Sambhal, Uttar Pradesh' },
  { id: 'singrauli', name: 'Singrauli, Madhya Pradesh' },
  { id: 'nadiad', name: 'Nadiad, Gujarat' },
  { id: 'secunderabad', name: 'Secunderabad, Telangana' },
  { id: 'naihati', name: 'Naihati, West Bengal' },
  { id: 'yamunanagar', name: 'Yamunanagar, Haryana' },
  { id: 'bidhan-nagar', name: 'Bidhan Nagar, West Bengal' },
  { id: 'pallavaram', name: 'Pallavaram, Tamil Nadu' },
  { id: 'bidar', name: 'Bidar, Karnataka' },
  { id: 'munger', name: 'Munger, Bihar' },
  { id: 'panchkula', name: 'Panchkula, Haryana' },
  { id: 'burhanpur', name: 'Burhanpur, Madhya Pradesh' },
  { id: 'kharagpur', name: 'Kharagpur, West Bengal' },
  { id: 'dindigul', name: 'Dindigul, Tamil Nadu' },
  { id: 'gandhinagar', name: 'Gandhinagar, Gujarat' },
  { id: 'hospet', name: 'Hospet, Karnataka' },
  { id: 'nangloi-jat', name: 'Nangloi Jat, Delhi' },
  { id: 'malda', name: 'Malda, West Bengal' },
  { id: 'ongole', name: 'Ongole, Andhra Pradesh' },
  { id: 'deoghar', name: 'Deoghar, Jharkhand' },
  { id: 'chapra', name: 'Chapra, Bihar' },
  { id: 'haldia', name: 'Haldia, West Bengal' },
  { id: 'khandwa', name: 'Khandwa, Madhya Pradesh' },
  { id: 'nandyal', name: 'Nandyal, Andhra Pradesh' },
  { id: 'morena', name: 'Morena, Madhya Pradesh' },
  { id: 'amroha', name: 'Amroha, Uttar Pradesh' },
  { id: 'anand', name: 'Anand, Gujarat' },
  { id: 'bhind', name: 'Bhind, Madhya Pradesh' },
  { id: 'bhalswa-jahangir-pur', name: 'Bhalswa Jahangir Pur, Delhi' },
  { id: 'madhyamgram', name: 'Madhyamgram, West Bengal' },
  { id: 'bhiwani', name: 'Bhiwani, Haryana' },
  { id: 'berhampore', name: 'Berhampore, West Bengal' },
  { id: 'ambala', name: 'Ambala, Haryana' },
  { id: 'morbi', name: 'Morbi, Gujarat' },
  { id: 'fatehpur', name: 'Fatehpur, Uttar Pradesh' },
  { id: 'raebareli', name: 'Raebareli, Uttar Pradesh' },
  { id: 'khora', name: 'Khora, Uttar Pradesh' },
  { id: 'chittoor', name: 'Chittoor, Andhra Pradesh' },
  { id: 'bhusawal', name: 'Bhusawal, Maharashtra' },
  { id: 'orai', name: 'Orai, Uttar Pradesh' },
  { id: 'bahraich', name: 'Bahraich, Uttar Pradesh' },
  { id: 'phagwara', name: 'Phagwara, Punjab' },
  { id: 'vellore', name: 'Vellore, Tamil Nadu' },
  { id: 'mehsana', name: 'Mehsana, Gujarat' },
  { id: 'raiganj', name: 'Raiganj, West Bengal' },
  { id: 'sirsa', name: 'Sirsa, Haryana' },
  { id: 'danapur', name: 'Danapur, Bihar' },
  { id: 'serampore', name: 'Serampore, West Bengal' },
  { id: 'sultan-pur-majra', name: 'Sultan Pur Majra, Delhi' },
  { id: 'guna', name: 'Guna, Madhya Pradesh' },
  { id: 'jaunpur', name: 'Jaunpur, Uttar Pradesh' },
  { id: 'panvel', name: 'Panvel, Maharashtra' },
  { id: 'shivpuri', name: 'Shivpuri, Madhya Pradesh' },
  { id: 'surendranagar', name: 'Surendranagar, Gujarat' },
  { id: 'unnao', name: 'Unnao, Uttar Pradesh' },
  { id: 'chinsurah', name: 'Chinsurah, West Bengal' },
  { id: 'alappuzha', name: 'Alappuzha, Kerala' },
  { id: 'kottayam', name: 'Kottayam, Kerala' },
  { id: 'machilipatnam', name: 'Machilipatnam, Andhra Pradesh' },
  { id: 'shimla', name: 'Shimla, Himachal Pradesh' },
  { id: 'adoni', name: 'Adoni, Andhra Pradesh' },
  { id: 'udupi', name: 'Udupi, Karnataka' },
  { id: 'tenali', name: 'Tenali, Andhra Pradesh' },
  { id: 'manapparai', name: 'Manapparai, Tamil Nadu' },
  { id: 'proddatur', name: 'Proddatur, Andhra Pradesh' },
  { id: 'navsari', name: 'Navsari, Gujarat' },
  { id: 'kumbakonam', name: 'Kumbakonam, Tamil Nadu' },
  { id: 'bongaigaon', name: 'Bongaigaon, Assam' }
];
