export interface Sport {
  id: string;
  name: string;
  icon: string;
}

export const SPORTS_LIST: Sport[] = [
  { id: 'cricket', name: 'Cricket', icon: 'sports_cricket' },
  { id: 'football', name: 'Football', icon: 'sports_soccer' },
  { id: 'kabaddi', name: 'Kabaddi', icon: 'sports_handball' },
  { id: 'kho_kho', name: 'Kho Kho', icon: 'directions_run' },
  { id: 'athletics', name: 'Athletics', icon: 'sprint' },
  { id: 'badminton', name: 'Badminton', icon: 'sports_tennis' },
  { id: 'table_tennis', name: 'Table Tennis', icon: 'sports_tennis' },
  { id: 'tennis', name: 'Tennis', icon: 'sports_tennis' },
  { id: 'hockey', name: 'Hockey', icon: 'sports_hockey' },
  { id: 'volleyball', name: 'Volleyball', icon: 'sports_volleyball' },
  { id: 'basketball', name: 'Basketball', icon: 'sports_basketball' },
  { id: 'swimming', name: 'Swimming', icon: 'pool' },
  { id: 'chess', name: 'Chess', icon: 'extension' },
  { id: 'silambam', name: 'Silambam', icon: 'sports_martial_arts' },
  { id: 'carrom', name: 'Carrom', icon: 'games' },
  { id: 'malkhamb', name: 'Malkhamb', icon: 'sports' },
  { id: 'sepak_takraw', name: 'Sepak Takraw', icon: 'sports' },
  { id: 'gilli_danda', name: 'Gilli Danda', icon: 'sports' },
  { id: 'kalaripayattu', name: 'Kalaripayattu', icon: 'sports' },
  { id: 'pehlwani', name: 'Pehlwani', icon: 'sports' },
  { id: 'mukna', name: 'Mukna', icon: 'sports' },
  { id: 'thang_ta', name: 'Thang Ta', icon: 'sports' },
  { id: 'mallakhamba', name: 'Mallakhamba', icon: 'sports' },
  { id: 'yubi_lakpi', name: 'Yubi Lakpi', icon: 'sports' },
  { id: 'lagori', name: 'Lagori', icon: 'sports' },
  { id: 'jallikattu', name: 'Jallikattu', icon: 'sports' },
  { id: 'kambala', name: 'Kambala', icon: 'sports' },
  { id: 'vallam_kali', name: 'Vallam Kali', icon: 'sports' },
  { id: 'rollball', name: 'Rollball', icon: 'sports' },
  { id: 'sqay', name: 'Sqay', icon: 'sports' },
  { id: 'archery', name: 'Archery', icon: 'sports' },
  { id: 'artistic_gymnastics', name: 'Artistic Gymnastics', icon: 'sports_gymnastics' },
  { id: 'artistic_swimming', name: 'Artistic Swimming', icon: 'pool' },
  { id: 'boxing', name: 'Boxing', icon: 'sports' },
  { id: 'breaking', name: 'Breaking', icon: 'sports' },
  { id: 'canoe_slalom', name: 'Canoe Slalom', icon: 'rowing' },
  { id: 'canoe_sprint', name: 'Canoe Sprint', icon: 'rowing' },
  { id: 'cycling_bmx_freestyle', name: 'Cycling Bmx Freestyle', icon: 'directions_bike' },
  { id: 'cycling_bmx_racing', name: 'Cycling Bmx Racing', icon: 'directions_bike' },
  { id: 'cycling_mountain_bike', name: 'Cycling Mountain Bike', icon: 'directions_bike' },
  { id: 'cycling_road', name: 'Cycling Road', icon: 'directions_bike' },
  { id: 'cycling_track', name: 'Cycling Track', icon: 'directions_bike' },
  { id: 'diving', name: 'Diving', icon: 'pool' },
  { id: 'equestrian', name: 'Equestrian', icon: 'sports' },
  { id: 'fencing', name: 'Fencing', icon: 'sports' },
  { id: 'golf', name: 'Golf', icon: 'sports_golf' },
  { id: 'handball', name: 'Handball', icon: 'sports' },
  { id: 'judo', name: 'Judo', icon: 'sports_martial_arts' },
  { id: 'marathon_swimming', name: 'Marathon Swimming', icon: 'pool' },
  { id: 'modern_pentathlon', name: 'Modern Pentathlon', icon: 'sports' },
  { id: 'rhythmic_gymnastics', name: 'Rhythmic Gymnastics', icon: 'sports_gymnastics' },
  { id: 'rowing', name: 'Rowing', icon: 'rowing' },
  { id: 'rugby_sevens', name: 'Rugby Sevens', icon: 'sports_rugby' },
  { id: 'sailing', name: 'Sailing', icon: 'sports' },
  { id: 'shooting', name: 'Shooting', icon: 'sports' },
  { id: 'skateboarding', name: 'Skateboarding', icon: 'skateboarding' },
  { id: 'sport_climbing', name: 'Sport Climbing', icon: 'sports' },
  { id: 'surfing', name: 'Surfing', icon: 'surfing' },
  { id: 'taekwondo', name: 'Taekwondo', icon: 'sports_martial_arts' },
  { id: 'trampoline', name: 'Trampoline', icon: 'sports' },
  { id: 'triathlon', name: 'Triathlon', icon: 'sports' },
  { id: 'water_polo', name: 'Water Polo', icon: 'pool' },
  { id: 'weightlifting', name: 'Weightlifting', icon: 'sports' },
  { id: 'wrestling', name: 'Wrestling', icon: 'sports_martial_arts' },
  { id: 'alpine_skiing', name: 'Alpine Skiing', icon: 'snowmobile' },
  { id: 'biathlon', name: 'Biathlon', icon: 'snowmobile' },
  { id: 'bobsleigh', name: 'Bobsleigh', icon: 'snowmobile' },
  { id: 'cross_country_skiing', name: 'Cross Country Skiing', icon: 'snowmobile' },
  { id: 'curling', name: 'Curling', icon: 'snowmobile' },
  { id: 'figure_skating', name: 'Figure Skating', icon: 'snowmobile' },
  { id: 'freestyle_skiing', name: 'Freestyle Skiing', icon: 'snowmobile' },
  { id: 'ice_hockey', name: 'Ice Hockey', icon: 'snowmobile' },
  { id: 'luge', name: 'Luge', icon: 'snowmobile' },
  { id: 'nordic_combined', name: 'Nordic Combined', icon: 'sports' },
  { id: 'short_track_speed_skating', name: 'Short Track Speed Skating', icon: 'snowmobile' },
  { id: 'skeleton', name: 'Skeleton', icon: 'snowmobile' },
  { id: 'ski_jumping', name: 'Ski Jumping', icon: 'sports' },
  { id: 'snowboard', name: 'Snowboard', icon: 'snowboarding' },
  { id: 'speed_skating', name: 'Speed Skating', icon: 'snowmobile' },
  { id: 'baseball', name: 'Baseball', icon: 'sports_baseball' },
  { id: 'softball', name: 'Softball', icon: 'sports_baseball' },
  { id: 'squash', name: 'Squash', icon: 'sports' },
  { id: 'billiards', name: 'Billiards', icon: 'sports' },
  { id: 'snooker', name: 'Snooker', icon: 'sports' },
  { id: 'polo', name: 'Polo', icon: 'sports' },
  { id: 'rugby_union', name: 'Rugby Union', icon: 'sports_rugby' },
  { id: 'rugby_league', name: 'Rugby League', icon: 'sports_rugby' },
  { id: 'netball', name: 'Netball', icon: 'sports' },
  { id: 'futsal', name: 'Futsal', icon: 'sports' },
  { id: 'beach_volleyball', name: 'Beach Volleyball', icon: 'sports' },
  { id: 'beach_soccer', name: 'Beach Soccer', icon: 'sports' },
  { id: 'dodgeball', name: 'Dodgeball', icon: 'sports' },
  { id: 'kickboxing', name: 'Kickboxing', icon: 'sports' },
  { id: 'muay_thai', name: 'Muay Thai', icon: 'sports' },
  { id: 'karate', name: 'Karate', icon: 'sports_martial_arts' },
  { id: 'wushu', name: 'Wushu', icon: 'sports_martial_arts' },
  { id: 'jiu_jitsu', name: 'Jiu Jitsu', icon: 'sports_martial_arts' },
  { id: 'mixed_martial_arts', name: 'Mixed Martial Arts', icon: 'sports_martial_arts' },
  { id: 'powerlifting', name: 'Powerlifting', icon: 'sports' },
  { id: 'bodybuilding', name: 'Bodybuilding', icon: 'sports' },
  { id: 'arm_wrestling', name: 'Arm Wrestling', icon: 'sports_martial_arts' },
  { id: 'bowling', name: 'Bowling', icon: 'sports' },
  { id: 'darts', name: 'Darts', icon: 'sports' },
  { id: 'tug_of_war', name: 'Tug Of War', icon: 'sports' },
  { id: 'ultimate_frisbee', name: 'Ultimate Frisbee', icon: 'sports' },
  { id: 'padel', name: 'Padel', icon: 'sports' },
  { id: 'pickleball', name: 'Pickleball', icon: 'sports' },
  { id: 'rounders', name: 'Rounders', icon: 'sports_baseball' },
  { id: 'korfball', name: 'Korfball', icon: 'sports' },
  { id: 'gymnastics', name: 'Gymnastics', icon: 'sports_gymnastics' },
  { id: 'parkour', name: 'Parkour', icon: 'sports_gymnastics' },
  { id: 'cheerleading', name: 'Cheerleading', icon: 'sports_gymnastics' },
  { id: 'aerobics', name: 'Aerobics', icon: 'sports_gymnastics' },
  { id: 'dance_sports', name: 'Dance Sports', icon: 'sports' },
  { id: 'yoga', name: 'Yoga', icon: 'sports_gymnastics' },
  { id: 'chess_boxing', name: 'Chess Boxing', icon: 'sports' },
  { id: 'esports', name: 'Esports', icon: 'sports_esports' },
  { id: 'auto_racing', name: 'Auto Racing', icon: 'sports_motorsports' },
  { id: 'motorcycle_racing', name: 'Motorcycle Racing', icon: 'sports_motorsports' },
  { id: 'kart_racing', name: 'Kart Racing', icon: 'sports_motorsports' },
  { id: 'motocross', name: 'Motocross', icon: 'directions_bike' },
  { id: 'bmx', name: 'Bmx', icon: 'directions_bike' },
  { id: 'roller_skating', name: 'Roller Skating', icon: 'snowmobile' },
  { id: 'inline_skating', name: 'Inline Skating', icon: 'snowmobile' },
  { id: 'speed_skating_roller', name: 'Speed Skating Roller', icon: 'snowmobile' },
  { id: 'water_skiing', name: 'Water Skiing', icon: 'pool' },
  { id: 'wakeboarding', name: 'Wakeboarding', icon: 'sports' },
  { id: 'kitesurfing', name: 'Kitesurfing', icon: 'surfing' },
  { id: 'windsurfing', name: 'Windsurfing', icon: 'surfing' },
  { id: 'bodyboarding', name: 'Bodyboarding', icon: 'surfing' },
  { id: 'scuba_diving', name: 'Scuba Diving', icon: 'pool' },
  { id: 'freediving', name: 'Freediving', icon: 'pool' },
  { id: 'paragliding', name: 'Paragliding', icon: 'sports' },
  { id: 'skydiving', name: 'Skydiving', icon: 'pool' },
  { id: 'bungee_jumping', name: 'Bungee Jumping', icon: 'sports' },
  { id: 'rock_climbing', name: 'Rock Climbing', icon: 'sports' },
  { id: 'bouldering', name: 'Bouldering', icon: 'sports' },
  { id: 'mountaineering', name: 'Mountaineering', icon: 'sports' },
  { id: 'orienteering', name: 'Orienteering', icon: 'sports' },
  { id: 'geocaching', name: 'Geocaching', icon: 'sports' },
  { id: 'fishing', name: 'Fishing', icon: 'sports' },
  { id: 'hunting', name: 'Hunting', icon: 'sports' },
  { id: 'biathlon_summer', name: 'Biathlon Summer', icon: 'snowmobile' },
  { id: 'pentathlon_winter', name: 'Pentathlon Winter', icon: 'sports' },
  { id: 'aquathlon', name: 'Aquathlon', icon: 'pool' },
  { id: 'duathlon', name: 'Duathlon', icon: 'sports' },
  { id: 'crossfit', name: 'Crossfit', icon: 'sports' },
  { id: 'strongman', name: 'Strongman', icon: 'sports' },
  { id: 'marathon', name: 'Marathon', icon: 'sports' },
  { id: 'half_marathon', name: 'Half Marathon', icon: 'sports' },
  { id: 'ultramarathon', name: 'Ultramarathon', icon: 'sports' },
  { id: 'cross_country_running', name: 'Cross Country Running', icon: 'sports' },
  { id: 'trail_running', name: 'Trail Running', icon: 'sports' },
  { id: 'racewalking', name: 'Racewalking', icon: 'sports' },
  { id: 'hurdling', name: 'Hurdling', icon: 'sports' },
  { id: 'steeplechase', name: 'Steeplechase', icon: 'sports' },
  { id: 'bocce', name: 'Bocce', icon: 'sports' },
  { id: 'boules', name: 'Boules', icon: 'sports' },
  { id: 'petanque', name: 'Petanque', icon: 'sports' },
  { id: 'croquet', name: 'Croquet', icon: 'sports' },
  { id: 'gateball', name: 'Gateball', icon: 'sports' },
  { id: 'lawn_bowls', name: 'Lawn Bowls', icon: 'sports' },
  { id: 'tenpin_bowling', name: 'Tenpin Bowling', icon: 'sports' },
  { id: 'skittles', name: 'Skittles', icon: 'sports' },
  { id: 'kurash', name: 'Kurash', icon: 'sports' },
  { id: 'sambo', name: 'Sambo', icon: 'sports' },
  { id: 'sumo', name: 'Sumo', icon: 'sports' },
  { id: 'aikido', name: 'Aikido', icon: 'sports_martial_arts' },
  { id: 'kendo', name: 'Kendo', icon: 'sports_martial_arts' },
  { id: 'capoeira', name: 'Capoeira', icon: 'sports_martial_arts' },
  { id: 'pencak_silat', name: 'Pencak Silat', icon: 'sports_martial_arts' },
  { id: 'arnis', name: 'Arnis', icon: 'sports' },
  { id: 'savate', name: 'Savate', icon: 'sports' },
  { id: 'lethwei', name: 'Lethwei', icon: 'sports' },
  { id: 'bando', name: 'Bando', icon: 'sports' },
  { id: 'vovinam', name: 'Vovinam', icon: 'sports' },
  { id: 'tchoukball', name: 'Tchoukball', icon: 'sports' },
  { id: 'goalball', name: 'Goalball', icon: 'sports' },
  { id: 'boccia', name: 'Boccia', icon: 'sports' },
  { id: 'sitting_volleyball', name: 'Sitting Volleyball', icon: 'sports' },
  { id: 'wheelchair_basketball', name: 'Wheelchair Basketball', icon: 'sports' },
  { id: 'wheelchair_rugby', name: 'Wheelchair Rugby', icon: 'sports_rugby' },
  { id: 'wheelchair_tennis', name: 'Wheelchair Tennis', icon: 'sports' },
  { id: 'wheelchair_fencing', name: 'Wheelchair Fencing', icon: 'sports' },
  { id: 'blind_football', name: 'Blind Football', icon: 'sports_rugby' },
  { id: 'cp_football', name: 'Cp Football', icon: 'sports_rugby' },
  { id: 'powerchair_football', name: 'Powerchair Football', icon: 'sports_rugby' },
  { id: 'sled_hockey', name: 'Sled Hockey', icon: 'sports' },
  { id: 'para_ice_hockey', name: 'Para Ice Hockey', icon: 'snowmobile' },
  { id: 'para_alpine_skiing', name: 'Para Alpine Skiing', icon: 'snowmobile' },
  { id: 'para_biathlon', name: 'Para Biathlon', icon: 'snowmobile' },
  { id: 'para_cross_country_skiing', name: 'Para Cross Country Skiing', icon: 'snowmobile' },
  { id: 'para_snowboard', name: 'Para Snowboard', icon: 'snowboarding' },
  { id: 'para_athletics', name: 'Para Athletics', icon: 'sports' },
  { id: 'para_swimming', name: 'Para Swimming', icon: 'pool' },
  { id: 'para_powerlifting', name: 'Para Powerlifting', icon: 'sports' },
  { id: 'para_archery', name: 'Para Archery', icon: 'sports' },
  { id: 'para_cycling', name: 'Para Cycling', icon: 'directions_bike' },
  { id: 'para_equestrian', name: 'Para Equestrian', icon: 'sports' },
  { id: 'para_judo', name: 'Para Judo', icon: 'sports_martial_arts' },
  { id: 'para_rowing', name: 'Para Rowing', icon: 'rowing' },
  { id: 'para_table_tennis', name: 'Para Table Tennis', icon: 'sports' },
  { id: 'para_taekwondo', name: 'Para Taekwondo', icon: 'sports_martial_arts' },
  { id: 'para_triathlon', name: 'Para Triathlon', icon: 'sports' },
];

export function getSportById(id: string | null | undefined): Sport | undefined {
  if (!id) return undefined;
  return SPORTS_LIST.find(s => s.id === id);
}

export function getSportName(idOrName: string | null | undefined): string {
  if (!idOrName) return '';
  
  // Try matching by id first
  const sportById = SPORTS_LIST.find(s => s.id === idOrName);
  if (sportById) return sportById.name;
  
  // Then case-insensitive name match
  const lowerInput = idOrName.toLowerCase();
  const sportByName = SPORTS_LIST.find(s => s.name.toLowerCase() === lowerInput);
  if (sportByName) return sportByName.name;
  
  // Otherwise humanize
  return idOrName
    .replace(/_/g, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}
