export const ROUTES = {
  SPLASH: '/splash',
  WELCOME: '/welcome',
  LOGIN: '/login',
  SIGNUP: '/signup',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  HOME: '/',
  PROFILE: '/profile',
  SEARCH: '/search',
  MESSAGES: '/messages',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  SELECT_SPORTS: '/select-sports',
  CREATE_SPORTS_PROFILE: '/create-sports-profile',
  PROFILE_PICTURE_UPLOAD: '/profile-picture-upload',
  PERSONAL_INFORMATION: '/personal-information',
  PLAYING_INFORMATION: '/playing-information',
  PROFILE_COMPLETION: '/profile-completion',
  EDIT_PROFILE: '/profile/edit',
  STATISTICS: '/profile/statistics',
  
  // Quick Actions (Temporary Placeholders)
  ASSIGN_TRAINING: '/assign-training',
  MY_ATHLETES: '/my-athletes',
  ANNOUNCEMENTS: '/announcements',
  CREATE_EVENT: '/events/create',
  CREATE_TOURNAMENT: '/tournaments/create',
  EVENTS: '/events',
  EVENT_DETAILS: '/events/:id',
  APPROVALS: '/approvals',
  TEAM_MANAGEMENT: '/team-management',
  ATHLETE_DIRECTORY: '/athletes',
  ATHLETE_PUBLIC_PROFILE: '/athletes/:id',
  ORGANIZATION_DIRECTORY: '/organizations',
  ORGANIZATION_DETAIL: '/organizations/:id',
  REPORTS: '/reports',
  LEADERBOARDS: '/leaderboards',
  ACHIEVEMENTS: '/achievements',
  SCHEDULE: '/schedule',
  TOURNAMENTS: '/tournaments',
  ANALYTICS: '/analytics',
  POSTS: '/posts',
  NETWORK: '/network',
  CREATE: '/create',
} as const;
